### ISSUE TITLE
Your Github profile and projects look amazing. 🚀

### ISSUE THREAD

**Issue by NayakPenguin** [rudraWorks/rps.bio#1]
Your Github profile and projects look amazing. 🚀

Can you please star mark my project : https://github.com/Nayaker/AlgoListed

Sorry for creating an issue :)

**Comment by rudraWorks** [comment]
Done

**Comment by rudraWorks** [comment]
What tech stack did you use for algolisted?

**Comment by NayakPenguin** [comment]
MERN stack + Flask + Beutifulsoup

**Comment by rudraWorks** [comment]
I'm truly amazed and captivated by Algolisted. I also have a passion for
creating practical micro SaaS websites. If you don't mind, could you share
the number of users currently signed up for your application?

**Comment by NayakPenguin** [comment]
I actually don't have the signup functionality on the website currently, when I implement that I would definitely share that with you :)

**Comment by rudraWorks** [comment]
Ok, thanks.
